name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/workflows/yarn

      - uses: ./.github/workflows/build
        with:
          secrets: ${{ toJSON(secrets) }}
          is-production: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Script to upload release files
      - name: 'Upload release build files for production'
        env:
          BUCKET: s3://${{ secrets.AWS_STAGING_BUCKET_NAME }}/releases/${{ github.event.release.tag_name }}
        run: bash ./scripts/github/s3_upload.sh
