name: 'Lint'
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      # `hardhat compile` has issues with the latest version of Node
      # https://github.com/NomicFoundation/hardhat/issues/3877
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - uses: ./.github/workflows/yarn

      - uses: Maggi64/eslint-plus-action@master
        with:
          npmInstall: false
