name: 'Lint'
on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/workflows/yarn

      - uses: Maggi64/eslint-plus-action@972d934f4b5b41945c4f489dc49717c80eb8be4c # master
        with:
          npmInstall: false
